# .github/workflows/comment-on-pr.yml
name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize] # Triggers when a PR is opened or updated
permissions:
  contents: write
  pull-requests: write


jobs:
  post-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Post a Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello, thank you for submitting this pull request! 👋
            
            - Please ensure all checks pass before merging.
            - If you have any questions, feel free to ask here.

            Have a great day! 🌟
