name: Monitor Self Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  monitor-self-review:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Check if self-review is completed
      id: check-review
      run: |
        echo "Checking if self-review is completed..."
        if [[ "${{ github.event.comment.body }}" == *"[x] Self-review completed"* ]]; then
          echo "Self-review checkbox checked. Triggering the next workflow..."
          echo "::set-output name=trigger::true"
        else
          echo "Self-review checkbox not checked."
          echo "::set-output name=trigger::false"
        fi

    - name: Trigger compile and test workflow
      if: steps.check-review.outputs.trigger == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'self-review-completed'
          })
