name: Request Self Review

on:
  pull_request:
    types: [opened]

jobs:
  request-self-review:
    runs-on: ubuntu-latest
    steps:
    - name: Add self-review comment
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Please perform a self-review.\n- [ ] Self-review completed'
          })
